import { AuthEventData } from '@aws-amplify/ui';

export const facade = {
  error: '',
  hasValidationErrors: false,
  isPending: false,
  route: '',
  authStatus: '',
  user: '',
  validationErrors: [''],
  codeDeliveryDetails: {
    val: '',
    DeliveryMedium: '',
  },
  change: (_?: AuthEventData) => null,
  updateForm: (_?: AuthEventData) => null,
  updateBlur: (_?: AuthEventData) => null,
  resend: (_?: AuthEventData) => null,
  resendCode: (_?: AuthEventData) => null,
  signOut: (_?: AuthEventData) => null,
  federatedSignIn: (_?: AuthEventData) => null,
  toFederatedSignIn: (_?: AuthEventData) => null,
  resetPassword: (_?: AuthEventData) => null,
  toResetPassword: (_?: AuthEventData) => null,
  signIn: (_?: AuthEventData) => null,
  toSignIn: (_?: AuthEventData) => null,
  signUp: (_?: AuthEventData) => null,
  toSignUp: (_?: AuthEventData) => null,
  skip: (_?: AuthEventData) => null,
  skipVerification: (_?: AuthEventData) => null,
  submit: (_?: AuthEventData) => null,
  submitForm: (_?: AuthEventData) => null,
};
